apiVersion: apps/v1

kind: Deployment

metadata:

  name: api-pelicula-v1

  labels:

    app: api-pelicula

    version: "1.0"

spec:

  replicas: 3

  selector:

    matchLabels:

      app: api-pelicula

  template:

    metadata:

      labels:

        app: api-pelicula

        version: "1.0"

    spec:

      containers:

      - name: api-pelicula

        image: dex11/api-peliculas:v2

        ports:

        - name: http-server

          containerPort: 5000